### PR TITLE
Add the fenics tests in `la` and `nls` for PETSc testing

### PR DESCRIPTION
**Pull request by sblauth**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Upstream PR: https://bitbucket.org/fenics-project/dolfin/pull-requests/578

### CODE REVIEW

**Comment by sblauth** [comment]
@conda-forge-admin, please rerender

**Comment by sblauth** [comment]
Okay, well it looks like we also have to patch the tests if we want to make this work. At the moment, the build fails as `numpy.float` is called - it should just call the plain python `float`. I am curious how many other things have to be changed...

**Comment by sblauth** [comment]
@minrk The build process with the tests enabled looks good - though it takes a lot more time. Is this still okay? Do we want to merge this and re-run the tests for the PETSc 3.22 and Python 3.13 builds?

**Comment by minrk** [comment]
Yeah, I think that's a good idea. If you want to select a slightly smaller subset on the emulated platforms, that would be okay by me, too.

**Comment by sblauth** [comment]
I have no idea how relevant these are - so I would not change anything. If you have an idea which of these to disable, feel free to do so.

**Comment by minrk** [comment]
We can trim them down a bit if and when we get annoyed by the time taken

**Pull request merged**
