### PR TITLE
adding an openmpi build

### PR DESCRIPTION
**Pull request by muh-hassani**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by muh-hassani** [comment]
@conda-forge-admin, please rerender

**Comment by muh-hassani** [comment]
To avoid the initial errors, I added the following to `meta.yaml`,
```
       - export OMPI_MCA_plm=isolated  # [ mpi == 'openmpi' ]
        - export OMPI_MCA_btl_vader_single_copy_mechanism=none  # [ mpi == 'openmpi' ]
        - export OMPI_MCA_rmaps_base_oversubscribe=yes  # [ mpi == 'openmpi' ]
```
but still, the build of fenics-libdolfin fails with:
 
```
  orte_ess_init failed
  --> Returned value Unable to start a daemon on the local node (-127) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Unable to start a daemon on the local node" (-127) instead of "Success" (0)
```

**Comment by johannesring** [comment]
It might help to add
```
export OMPI_MCA_plm_rsh_agent=/bin/false
export OMPI_MCA_btl_base_warn_component_unused=0
```
These are used when building the Debian package.

**Comment by muh-hassani** [comment]
> 
> 
> It might help to add
> 
> ```
> export OMPI_MCA_plm_rsh_agent=/bin/false
> export OMPI_MCA_btl_base_warn_component_unused=0
> ```
> 
> These are used when building the Debian package.

@johannesring, Thanks for your suggestion. Unfortunately, it did not work, still I get the error:
```
PETSC_TEST_LIB_OUTPUT: --------------------------------------------------------------------------
The value of the MCA parameter "plm_rsh_agent" was set to a path
that could not be found:

  plm_rsh_agent: ssh : rsh

Please either unset the parameter, or check that the path is correct
--------------------------------------------------------------------------
[b9d6ee7464ea:01877] [[INVALID],INVALID] FORCE-TERMINATE AT Not found:-13 - error plm_rsh_component.c(335)
[b9d6ee7464ea:01876] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 716
[b9d6ee7464ea:01876] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 172
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Unable to start a daemon on the local node (-127) instead of ORTE_SUCCESS


```
@jan-janssen, do you have any idea, how I can avoid this failure in the build process with openmpi?

**Comment by johannesring** [comment]
I think the problem is that `false` is not in `/bin/`. It looks like `false` is in the `coreutils` package and that you need to set `OMPI_MCA_plm_rsh_agent` to `$CONDA_PREFIX/bin/false`.

**Pull request closed without merging**
