### PR TITLE
2017.2.0

### PR DESCRIPTION
**Pull request by minrk**
updates several dependencies and pins (petsc 3.8, etc.)

This build for me (macOS, py36), we'll see if CI agrees.

@garth-wells any other changes to dependencies/tests/build configuration I should make?

### CODE REVIEW

**Comment by minrk** [comment]
Somewhat surprisingly, everything passed on the first go on Linux! Still waiting for the macOS backlog.

**Comment by basnijholt** [comment]
Also macOS seems to have worked!

Currently our Jupyterhub environments have a broken `fenics` install (`import dolfin` errors) because of dependencies issues probably. Let's hope this fixes it 👍

**Comment by minrk** [comment]
From notes in the fenics slack and @chrisrichardson, we'll wait for dolfin-2017.2.0post1 which has a fix for dolfin-convert.

**Comment by basnijholt** [comment]
I am trying to see whether this PR solves our issues, so I build it myself and installed it, however it seems to be downgrading a lot of packages, @minrk do you know why?

```bash
•% ➜ conda install -c basnijholt fenics
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    scalapack: 2.0.2-0                       conda-forge

The following packages will be UPDATED:

    boost:     1.63.0-py36_5                 conda-forge --> 1.64.0-py36_4                 conda-forge
    boost-cpp: 1.63.0-2                      conda-forge --> 1.64.0-1                      conda-forge
    fenics:    2016.2.0-py36_6               conda-forge --> 2017.1.0-np113py36_6          conda-forge
    mshr:      2016.2.0-py36_1               conda-forge --> 2017.1.0-py36_1               conda-forge
    swig:      3.0.11-0                      conda-forge --> 3.0.12-2                      conda-forge

The following packages will be DOWNGRADED:

    h5py:      2.7.1-py36_2                  conda-forge --> 2.7.1-py36_1                  conda-forge
    hdf5:      1.10.1-1                      conda-forge --> 1.8.18-2                      conda-forge
    kwant:     1.3.1-py36_blas_openblas_202  conda-forge [blas_openblas] --> 1.3.1-py36_blas_openblas_201  conda-forge [blas_openblas]
    libnetcdf: 4.5.0-3                       conda-forge --> 4.4.1.1-9                     conda-forge
    mumps:     5.0.2-blas_openblas_208       conda-forge [blas_openblas] --> 5.0.2-blas_openblas_205       conda-forge [blas_openblas]
    netcdf4:   1.3.1-py36_2                  conda-forge --> 1.3.1-py36_0                  conda-forge
    numpy:     1.13.3-py36_blas_openblas_201 conda-forge [blas_openblas] --> 1.13.3-py36_blas_openblas_200 conda-forge [blas_openblas]
    openblas:  0.2.20-4                      conda-forge --> 0.2.19-2                      conda-forge
    opencv:    3.3.0-py36_blas_openblas_202  conda-forge [blas_openblas] --> 3.3.0-py36_blas_openblas_200  conda-forge [blas_openblas]
    pytables:  3.4.2-py36_7                  conda-forge --> 3.4.2-py36_6                  conda-forge
    scipy:     1.0.0-py36_blas_openblas_201  conda-forge [blas_openblas] --> 0.19.1-py36_blas_openblas_202 conda-forge [blas_openblas]
```

**Comment by minrk** [comment]
That's installing 2017.1.0, not 2017.2.0. If you built it yourself, you should need `--use-local` to `conda install`. The downgrade looks like it's because it's pulling fenics 2017.1.0, which pins hdf5 to 1.8. fenics 2016 had some problems because it didn't pin some of its dependencies correctly (i.e. it may allow hdf5 1.10, but it won't work).

**Comment by basnijholt** [comment]
Oh, yes something went wrong there, sorry. I actually uploaded the build to my channel because I build it in the `condaforge/linux-anvil` Docker image. 

I first uninstalled the existing `fenics` and then installed it from my channel, which doesn't have any unexpected downgrades:
```python
•% ➜ conda install -c basnijholt fenics
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    fenics:      2017.2.0-np113py36_0         basnijholt
    libboost:    1.65.1-h4055789_3            defaults
    py-boost:    1.65.1-py36hff4598c_3        defaults
    suitesparse: 4.5.4-blas_openblas_200      conda-forge [blas_openblas]
    tbb:         2018_20170919-0              conda-forge

The following packages will be UPDATED:

    boost:       1.64.0-py36_4                conda-forge --> 1.65.1-py36hfaba7b9_3        defaults
    h5py:        2.7.1-py36_1                 conda-forge --> 2.7.1-py36_2                 conda-forge
    hdf5:        1.8.18-2                     conda-forge --> 1.10.1-1                     conda-forge
    libnetcdf:   4.4.1.1-9                    conda-forge --> 4.5.0-3                      conda-forge
    netcdf4:     1.3.1-py36_0                 conda-forge --> 1.3.1-py36_2                 conda-forge
    opencv:      3.3.0-py36_blas_openblas_200 conda-forge [blas_openblas] --> 3.3.0-py36_blas_openblas_201 conda-forge [blas_openblas]
    petsc:       3.7.2-blas_openblas_0        conda-forge [blas_openblas] --> 3.8.1-blas_openblas_0        conda-forge [blas_openblas]
    petsc4py:    3.7.0-py36_1                 conda-forge --> 3.8.1-py36_1                 conda-forge
    pytables:    3.4.2-py36_6                 conda-forge --> 3.4.2-py36_7                 conda-forge
    slepc:       3.7.4-0                      conda-forge --> 3.8.0-blas_openblas_0        conda-forge [blas_openblas]
    slepc4py:    3.7.0-py36_0                 conda-forge --> 3.8.0-py36_0                 conda-forge
```
Importing fenics still gives me the following error (also happens with older versions):
```python
•% ➜ ipython
Python 3.6.3 | packaged by conda-forge | (default, Nov  4 2017, 10:10:56)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import fenics
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/dolfin/cpp/common.py in swig_import_helper()
     17         try:
---> 18             return importlib.import_module(mname)
     19         except ImportError:

/opt/conda/lib/python3.6/importlib/__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127

/opt/conda/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/opt/conda/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/opt/conda/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/opt/conda/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/opt/conda/lib/python3.6/importlib/_bootstrap.py in module_from_spec(spec)

/opt/conda/lib/python3.6/importlib/_bootstrap_external.py in create_module(self, spec)

/opt/conda/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: /opt/conda/lib/python3.6/site-packages/dolfin/cpp/../../../../libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/conda/lib/python3.6/site-packages/dolfin/cpp/../../../../libboost_timer.so.1.65.1)

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-743ea8bb985a> in <module>()
----> 1 import fenics

/opt/conda/lib/python3.6/site-packages/fenics/__init__.py in <module>()
      5 """
      6
----> 7 from dolfin import *

/opt/conda/lib/python3.6/site-packages/dolfin/__init__.py in <module>()
     15
     16 # Import names from the compiled cpp modules
---> 17 from . import cpp
     18 from dolfin.cpp import *
     19 from dolfin.cpp import __version__, __swigversion__, __pythonversion__

/opt/conda/lib/python3.6/site-packages/dolfin/cpp/__init__.py in <module>()
     41
     42     # Import the module
---> 43     exec("from . import %s" % module_name)
     44     module = globals()[module_name]
     45

/opt/conda/lib/python3.6/site-packages/dolfin/cpp/__init__.py in <module>()

/opt/conda/lib/python3.6/site-packages/dolfin/cpp/common.py in <module>()
     19         except ImportError:
     20             return importlib.import_module('_common')
---> 21     _common = swig_import_helper()
     22     del swig_import_helper
     23 elif _swig_python_version_info >= (2, 6, 0):

/opt/conda/lib/python3.6/site-packages/dolfin/cpp/common.py in swig_import_helper()
     18             return importlib.import_module(mname)
     19         except ImportError:
---> 20             return importlib.import_module('_common')
     21     _common = swig_import_helper()
     22     del swig_import_helper

/opt/conda/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127
    128

ModuleNotFoundError: No module named '_common'
```

**Comment by minrk** [comment]
I just saw that one, and it seems to have to do with `icu`. What do you get if you do `conda install -c conda-forge 'icu=58.*'`?

**Comment by basnijholt** [comment]
```bash
tinkerer at io in Work/hpc05/ipykernel on  asyncio-clean-exit took 9m 16s
•% ➜ conda install -c conda-forge 'icu=58.*'
Fetching package metadata ...............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /opt/conda:
#
icu                       58.2                          0    conda-forge
```

**Comment by minrk** [comment]
What's `conda list`?

**Comment by minrk** [comment]
I see from the error (which I've seen with icu before) that it's actually coming from boost and that you have boost from defaults. Can you get boost from conda-forge as well?

**Comment by basnijholt** [comment]
You can also run `docker run -it quantumtinkerer/research bash` and do
```
conda uninstall --yes fenics
conda install -c basnijholt --yes fenics
``` 

```bash
•% ➜ conda list
# packages in environment at /opt/conda:
#
alembic                   0.9.6                      py_0    conda-forge
anaconda                  custom           py36hbbc8b67_0    defaults
asn1crypto                0.22.0                   py36_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.4                      py36_1    conda-forge
bcrypt                    3.1.4            py36h621fe67_0    defaults
blas                      1.1                    openblas    conda-forge
bleach                    2.0.0                    py36_0    conda-forge
bokeh                     0.12.10                  py36_0    conda-forge
boost                     1.65.1           py36hfaba7b9_3    defaults
boost-cpp                 1.64.0                        1    conda-forge
bottleneck                1.2.1                    py36_1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
cairo                     1.14.6                        5    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                      py36_0    conda-forge
cloog                     0.18.0                        0    defaults
cloudpickle               0.4.0                    py36_0    conda-forge
cmake                     3.9.6                         1    conda-forge
colorama                  0.3.9                    py36_0    conda-forge
conda                     4.3.29                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
configurable-http-proxy   3.1.0                         0    conda-forge
cryptography              2.0.3                    py36_0    conda-forge
curl                      7.55.1                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dask                      0.16.0                     py_0    conda-forge
dask-core                 0.16.0                     py_0    conda-forge
dbus                      1.10.22                       0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
deepdish                  0.3.4                    py36_1    conda-forge
dill                      0.2.6                    py36_0    conda-forge
distributed               1.20.0                   py36_0    conda-forge
eigen                     3.3.3                         0    conda-forge
emcee                     2.2.1                    py36_3    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
execnet                   1.3.0                    py36_1    defaults
expat                     2.2.1                         0    conda-forge
fastcache                 1.0.2                    py36_0    conda-forge
feedparser                5.2.1                    py36_0    defaults
fenics                    2017.2.0            np113py36_0    basnijholt
ffmpeg                    3.2.4                         2    conda-forge
fontconfig                2.12.1                        5    conda-forge
freetype                  2.7                           2    conda-forge
gcc                       4.8.5                         7    defaults
gettext                   0.19.7                        1    conda-forge
giflib                    5.1.4                         0    conda-forge
gitdb2                    2.0.2                    py36_0    conda-forge
gitpython                 2.1.7                    py36_0    conda-forge
glib                      2.51.4                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
gmpy2                     2.0.8                    py36_1    conda-forge
graphviz                  2.38.0                        6    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
h5netcdf                  0.5.0                      py_0    conda-forge
h5py                      2.7.1                    py36_2    conda-forge
harfbuzz                  1.3.4                         2    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        1    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
holoviews                 1.9.2                     <pip>
hpc05                     1.18+10.g18f0b5c.dirty           <pip>
html5lib                  0.999999999              py36_0    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.6                      py36_1    conda-forge
ipykernel                 4.8.0.dev0                <pip>
ipyparallel               6.0.2                    py36_0    conda-forge
ipython                   6.2.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.0.5                    py36_0    conda-forge
isl                       0.12.2                        0    defaults
jasper                    1.900.1                       4    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jpeg                      9b                            2    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
jupyter                   1.0.0                    py36_0    conda-forge
jupyter-dashboards-bundlers 0.9.1                     <pip>
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_cms               0.7.0                    py36_0    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_dashboards        0.7.0                    py36_0    conda-forge
jupyterhub                0.8.1                    py36_0    conda-forge
jupyterlab                0.29.2                   py36_0    conda-forge
jupyterlab_launcher       0.5.5                    py36_0    conda-forge
keyring                   10.5.0                    <pip>
keyrings.alt              2.3                       <pip>
krb5                      1.14.2                        0    conda-forge
kwant                     1.3.1           py36_blas_openblas_201  [blas_openblas]  conda-forge
lancet                    0.9.0                    py36_0    conda-forge
libboost                  1.65.1               h4055789_3    defaults
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran               3.0.0                         1    defaults
libiconv                  1.14                          4    conda-forge
libnetcdf                 4.5.0                         3    conda-forge
libpng                    1.6.28                        2    conda-forge
libsodium                 1.0.10                        0    conda-forge
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libtiff                   4.0.7                         1    conda-forge
libtool                   2.4.6                         0    conda-forge
libuv                     1.11.0                        0    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.5                         1    conda-forge
line_profiler             2.0                      py36_0    conda-forge
locket                    0.2.0                    py36_1    conda-forge
lzo                       2.10                          0    conda-forge
mako                      1.0.7                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.1.0                    py36_1    conda-forge
metis                     5.1.0                         3    conda-forge
mistune                   0.8.1            py36h3d5977c_0    defaults
mpc                       1.0.3                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpich                     3.2                           5    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
msgpack-python            0.4.8                    py36_0    conda-forge
mshr                      2017.1.0                 py36_1    conda-forge
mumps                     5.0.2           blas_openblas_205  [blas_openblas]  conda-forge
nb_conda                  2.2.1                    py36_0    conda-forge
nb_conda_kernels          2.1.0                    py36_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbdime                    0.4.0                    py36_0    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
nbserverproxy             0.3.2                     <pip>
nbstripout                0.3.1                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
netcdf4                   1.3.1                    py36_2    conda-forge
nodejs                    6.11.0                        0    conda-forge
notebook                  5.2.1                    py36_2    conda-forge
numexpr                   2.6.4                    py36_0    conda-forge
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
olefile                   0.44                     py36_0    conda-forge
openblas                  0.2.19                        2    conda-forge
opencv                    3.3.0           py36_blas_openblas_201  [blas_openblas]  conda-forge
openssl                   1.0.2l                        0    conda-forge
pamela                    0.3.0                    py36_0    conda-forge
pandas                    0.21.0                   py36_0    conda-forge
pandoc                    2.0.0.1                       1    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
pango                     1.40.3                        3    conda-forge
param                     1.5.1                    py36_0    conda-forge
paramiko                  2.3.1                      py_0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
petsc                     3.8.1           blas_openblas_0  [blas_openblas]  conda-forge
petsc4py                  3.8.1                    py36_1    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    4.3.0                    py36_1    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pixman                    0.34.0                        0    conda-forge
pkg-config                0.29.1                        2    conda-forge
plotly                    2.2.0                    py36_0    conda-forge
ply                       3.10                     py36_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.0                    py36_0    conda-forge
ptscotch                  6.0.4                         4    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.5.2                      py_0    conda-forge
py-boost                  1.65.1           py36hff4598c_3    defaults
pyasn1                    0.3.7                      py_0    conda-forge
pycosat                   0.6.2                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyflakes                  1.6.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pynacl                    1.1.2                    py36_0    conda-forge
PyOpenGL                  3.1.0                     <pip>
pyopenssl                 17.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
pytables                  3.4.2                    py36_7    conda-forge
pytest                    3.2.5                    py36_0    conda-forge
pytest-cache              1.0                      py36_0    defaults
pytest-flakes             1.0.1                    py36_0    conda-forge
python                    3.6.3                         1    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
python-editor             1.0.3                    py36_0    conda-forge
python-gitlab             1.1.0                     <pip>
python-graphviz           0.8                      py36_0    conda-forge
python-oauth2             1.0.1                    py36_0    conda-forge
pytz                      2017.3                     py_2    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                         6    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtplot                    0.1.1.dev9                <pip>
QtPy                      1.3.1                     <pip>
readline                  6.2                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
rhash                     1.3.4                         0    conda-forge
ruamel_yaml               0.11.14                  py36_0    conda-forge
scalapack                 2.0.2                         0    conda-forge
scipy                     0.19.1          py36_blas_openblas_202  [blas_openblas]  conda-forge
scotch                    6.0.4                         3    conda-forge
SecretStorage             2.3.1                     <pip>
setuptools                36.6.0                   py36_1    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
slepc                     3.8.0           blas_openblas_0  [blas_openblas]  conda-forge
slepc4py                  3.8.0                    py36_0    conda-forge
smmap2                    2.0.3                    py36_0    conda-forge
sortedcontainers          1.5.7                    py36_0    conda-forge
sqlalchemy                1.1.13                   py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
sshtunnel                 0.1.1                    py36_0    conda-forge
suitesparse               4.5.4           blas_openblas_200  [blas_openblas]  conda-forge
swig                      3.0.12                        2    conda-forge
sympy                     1.1.1                    py36_0    conda-forge
tbb                       2018_20170919                 0    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
terminado                 0.6                      py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tinyarray                 1.2.0                    py36_1    conda-forge
tk                        8.5.19                        2    conda-forge
toolz                     0.8.2                      py_2    conda-forge
tornado                   4.5.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
vispy                     0.5.1                     <pip>
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.30.0                     py_1    conda-forge
whoosh                    2.7.4                    py36_0    conda-forge
widgetsnbextension        3.0.8                    py36_0    conda-forge
x264                      20131217                      3    conda-forge
xarray                    0.10.0                   py36_0    conda-forge
xlrd                      1.0.0                    py36_1    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zeromq                    4.2.1                         1    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by basnijholt** [comment]
Great, `conda install -c conda-forge boost` fixed it!

I'll check whether that also fixes the issue for the older version of fenics.

**Comment by minrk** [comment]
It's a bit worrying that some of these defaults versions aren't working, and it also doesn't seem right that the defaults versions would get installed with your channel priority.

**Comment by basnijholt** [comment]
Indeed, you are right. With the latest version available on the `conda-forge` channel it still doesn't work.

**Comment by minrk** [comment]
Success!

**Pull request merged**
