### PR TITLE
link openblas, suitesparse

### PR DESCRIPTION
**Pull request by minrk**
Dolfin wasn't detecting conda's openblas, so Linux builds have no BLAS right now
and OS X is using Accelerate.

### CODE REVIEW

**Comment by garth-wells** [comment]
Doe PETSc pick up an optimised BLAS? This will be more important for performance.

**Comment by mikaem** [comment]
I don't see this. Both PETSc and dolfin pick up libopenblas when I install on linux from main conda-forge channel. At least that's what ldd tells me.

**Comment by minrk** [comment]
PETSc found openblas correctly, so most things should be fine, and it should show up in ldd. When dolfin builds itself, though, it tries and fails to find any blas (see the message "A library with BLAS API" [in CMake output](https://circleci.com/gh/conda-forge/fenics-feedstock/33).

Dolfin finding blas/lapack itself is needed for it to try to link the suitesparse libraries. I'm not sure what those are used for directly in dolfin, as opposed to by PETSc, so this may not matter much. Is it important that dolfin link blas/lapack/umfpack/amd/cholmod *directly*? I see some HAVE_UMFPACK, HAVE_CHOLMOD in EigenLUSolver.cpp, but that's about it.

**Comment by garth-wells** [comment]
Eigen3 depends optionally on suitesparse and cholmod.

**Comment by minrk** [comment]
Maybe skip the direct suitesparse/blas link here, then? Or is the blas/lapack/suitesparse cmake stuff in dolfin vestigial?

**Comment by garth-wells** [comment]
I'm wondering if we're making things too elaborate. If the packing provides PETSc support, there probably isn't a good reason to have DOLIN link to suitesparse.

**Comment by minrk** [comment]
Makes sense. I'll close this one.

**Pull request closed without merging**
