### PR TITLE
MNT: Re-rendered with conda-smithy 2.0.1

### PR DESCRIPTION
**Pull request by johannesring**
Will build fenics for Python 3.6.

### CODE REVIEW

**Comment by johannesring** [comment]
The problem on CircleCI is this:
``` console
  Compiling 1 forms in demo/undocumented/auto-adaptive-navier-stokes/cpp...

  ffc -l dolfin -s -O -r auto -e AdaptiveNavierStokes.ufl

  Traceback (most recent call last):

    File "/feedstock_root/build_artefacts/fenics_1486997854241/work/dolfin-2016.2.0/cmake/scripts/generate-form-files.py", line 92, in <module>
      ret = ffc.main(args)
    File "/feedstock_root/build_artefacts/fenics_1486997854241/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.5/site-packages/ffc/__main__.py", line 234, in main
      code_h, code_c = compile_ufl_data(ufd, prefix, parameters)
    File "/feedstock_root/build_artefacts/fenics_1486997854241/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.5/site-packages/ffc/__main__.py", line 90, in compile_ufl_data
      parameters)
    File "/feedstock_root/build_artefacts/fenics_1486997854241/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.5/site-packages/ffc/errorcontrol/errorcontrol.py", line 86, in compile_with_error_control
      code_h, code_c = compile_form(ec_forms + forms, object_names, prefix, parameters)
    File "/feedstock_root/build_artefacts/fenics_1486997854241/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.5/site-packages/ffc/compiler.py", line 141, in compile_form
      prefix, parameters, jit)
    File "/feedstock_root/build_artefacts/fenics_1486997854241/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.5/site-packages/ffc/compiler.py", line 188, in compile_ufl_objects
      ir = compute_ir(analysis, prefix, parameters, jit)
    File "/feedstock_root/build_artefacts/fenics_1486997854241/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.5/site-packages/ffc/representation.py", line 187, in compute_ir
      for (form_id, fd) in enumerate(form_datas)]
    File "/feedstock_root/build_artefacts/fenics_1486997854241/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.5/site-packages/ffc/representation.py", line 187, in <listcomp>
      for (form_id, fd) in enumerate(form_datas)]
    File "/feedstock_root/build_artefacts/fenics_1486997854241/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.5/site-packages/ffc/representation.py", line 450, in _compute_integral_ir
      parameters)
    File "/feedstock_root/build_artefacts/fenics_1486997854241/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.5/site-packages/ffc/tensor/tensorrepresentation.py", line 91, in compute_integral_ir
      reorder_entries(terms[i][j])
    File "/feedstock_root/build_artefacts/fenics_1486997854241/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.5/site-packages/ffc/tensor/tensorreordering.py", line 59, in reorder_entries
      tensor[position] = A0.A0

  TypeError: slice indices must be integers or None or have an __index__
  method



-- Configuring incomplete, errors occurred!
```
This is with Python 3.5, so I'm not sure why this happens now and not before. Full build log is available [here](https://circleci.com/api/v1.1/project/github/conda-forge/fenics-feedstock/49/output/12/0?file=true).

**Comment by johannesring** [comment]
Looks like it failed with the same error on Travis.

**Comment by minrk** [comment]
The failure is due to the upgrade to numpy 1.12, which doesn't tolerate ffc passing floats in slices. It's fixed in [this commit](https://bitbucket.org/fenics-project/ffc/commits/c8ef816ed45336d5fd7e9689c40cb1150d71d71f). We should be able to apply that patch.

**Comment by johannesring** [comment]
Thanks @minrk - I'm not sure how to best handle this since FFC is installed using `pip` in `build.sh`.

**Comment by johannesring** [comment]
I have pushed the fix to the FFC `maint` branch. Maybe we can use that in `component-requirements.txt`?

**Comment by minrk** [comment]
I think we can. I'm testing something now, and I can push if it works.

**Comment by minrk** [comment]
#33 is built on top of this, with ffc from the current tag of the maintenance branch.

**Pull request merged**
