### PR TITLE
add libblas as a host dependency

### PR DESCRIPTION
**Pull request by basnijholt**
see https://github.com/conda-forge/fenics-feedstock/issues/82

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/fenics-feedstock/issues/82.

@isuruf, is this what you meant? Not sure whether I had to add `libcblas`.

### CODE REVIEW

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
For some reason `conda-smithy` removed all CI files...

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
@minrk, do you have any idea why the builds are failing?

**Comment by mariusvniekerk** [comment]
@conda-forge-admin, please rerender

**Comment by minrk** [comment]
Thanks for figuring this out! Sorry for my slow responses, I'm on parental leave, so only working ~20% which makes it hard to keep up.

**Pull request merged**
