### PR TITLE
pin numpy version

### PR DESCRIPTION
**Pull request by minrk**
updates to numpy need a rebuild of fenics

### CODE REVIEW

**Comment by garth-wells** [comment]
I'm still getting an error (see https://notebooks.azure.com/garth-wells/libraries/FEniCS for example). Do I need to do something else?

**Comment by minrk** [comment]
Hm. Installing fenics didn't install the latest build and upgrade numpy, as I would have expected. Instead, it decided to leave numpy as it was and install the latest fenics build that doesn't claim an incompatibility with that version of numpy (even though it *has* one that's not properly indicated). I'll investigate further.

**Comment by minrk** [comment]
#52 has a clearer explanation - pymc is already installed and linked against older numpy, preventing the upgrade of numpy to 1.13, which in turn prevents the latest fenics build from being pulled. If we remove the older builds of fenics-2017.1.0 from anaconda.org, then attempting to install fenics-2017.1 would result in the more informative error about the conflict in numpy dependency.

To work around it for now, remove pymc first:

    conda remove -y pymc
    conda config channels --add conda-forge
    conda install -y fenics=2017.1

**Comment by minrk** [comment]
Earlier builds of fenics-2017.1 have been marked as broken (thanks @ocefpaf!), so conda shouldn't consider them by default anymore. There's also been an update to the pymc package on conda-forge, so it should now accept numpy 1.13 as well, removing the conflict.

**Pull request merged**
